# 任务一 复合函数的计算图，计算器雅可比行列式

## 1.1 numpy实现

In [81]:
import numpy as np

class Computational_Graph:
    def __init__(self) -> None:
    #初始化x1，x2，x3
        self.x1 = 0
        self.x2 = 0
        self.x3 = 0
        #初始化z1，z2，z3，用以存储z1，z2，z3的计算结果
        self.z1 = 0
        self.z2 = 0
        self.z3 = 0
        #初始化u1，u2，u3，用以存储u1，u2，u3的计算结果
        self.u1 = 0
        self.u2 = 0
        self.u3 = 0
        #初始化v1，v2，v3，用以存储v1，v2，v3的计算结果
        self.u1 = 0
        self.u2 = 0
        self.u3 = 0
        #初始化y1，y2，用以存储y1，y2的计算结果
        self.y1 = 0
        self.y2 = 0 
        
    def function_z1(self,x1,x2):   
        return 2*x1 + x2
    def function_z2(self,x1,x3):
        return  x1 * 3 * x3   
    def function_z3(self,x3):
        return  -x3
    def function_u1(self,z1):
        return  np.sin(self.z1)
    def function_u2(self,x3,z2):
        return (2 * x3)+z2
    def function_u3(self,z1,z3):
        return (2 * z1) + z3
    def function_v1(self,u1,u3):    
        return u1 - u3
    def function_v2(self,u2): 
        return np.sin(-1*u2)      
    def function_v3(self,u1,u3):
        return u1 * u3
    def function_y1(self,v1,v2):
        return v1**2 + v2**3
    def function_y2(self, v2, v3):
        return v2*v3

#前向传播
    def forward(self,x1,x2,x3):
        self.x1 = x1
        self.x2 = x2
        self.x3 = x3

        self.z1 = self.function_z1(self.x1, self.x2)
        self.z2 = self.function_z2(self.x1, self.x3)
        self.z3 = self.function_z3(self.x3)

        self.u1 = self.function_u1(self.z1)
        self.u2 = self.function_u2(self.x3, self.z2)
        self.u3 = self.function_u3(self.z1, self.z3)

        self.v1 = self.function_v1(self.u1, self.u3)
        self.v2 = self.function_v2(self.u2)
        self.v3 = self.function_v3(self.u1, self.u3)

        self.y1 = self.function_y1(self.v1, self.v2)
        self.y2 = self.function_y2(self.v2, self.v3)

        print(f'y1 = {self.y1}, y2 = {self.y2}')



#反向传播
    def backward(self):
        self.y1_to_v1 = 2 * self.v1
        self.y1_to_v2 = 3*(self.v2**2)

        self.y2_to_v2 = self.v3
        self.y2_to_v3 = self.v2

        # backward
        self.v1_to_u1 = 1
        self.v1_to_u3 = -1

        self.v2_to_u2 = -1 * np.cos(-1 * self.u2)
        
        self.v3_to_u1 = self.u3
        self.v3_to_u3 = self.u1


        # back
        self.u1_to_z1 = np.cos(self.z1)

        self.u2_to_x3 = 2 
        self.u2_to_z2 = 1

        self.u3_to_z1 = 2
        self.u3_to_z3 = 1


        # back
        self.z1_to_x1 = 2
        self.z1_to_x2 = 1

        self.z2_to_x1 = 3*self.x3
        self.z2_to_x3 = 3*self.x1

        self.z3_to_x3 = -1

        # all 
        self.y1_to_x1 = self.y1_to_v1 * (self.v1_to_u1*(self.u1_to_z1*self.z1_to_x1) + self.v1_to_u3 * self.u3_to_z1*self.z1_to_x1) + self.y1_to_v2*self.v2_to_u2*self.u2_to_z2*self.z2_to_x1
        self.y1_to_x2 = self.y1_to_v1 * (self.v1_to_u1*(self.u1_to_z1*self.z1_to_x2)+ self.v1_to_u3*self.u3_to_z1*self.z1_to_x2)
        self.y1_to_x3 = self.y1_to_v1 * (self.v1_to_u3*self.u3_to_z3*self.z3_to_x3) + self.y1_to_v2*self.v2_to_u2*(self.u2_to_x3 +self.u2_to_z2*self.z2_to_x3)

        self.y2_to_x1 = self.y2_to_v2 * (self.v2_to_u2 * self.u2_to_z2 * self.z2_to_x1) + self.y2_to_v3* (self.v3_to_u1 *self.u1_to_z1 * self.z1_to_x1 + self.v3_to_u3 *self.u3_to_z1*self.z1_to_x1)
        self.y2_to_x2 = self.y2_to_v3 * (self.v3_to_u1 * self.u1_to_z1 *self.z1_to_x2 + self.v3_to_u3*self.u3_to_z1*self.z1_to_x2)
        self.y2_to_x3 = self.y2_to_v2 * (self.v2_to_u2 * (self.u2_to_x3+ self.u2_to_z2*self.z2_to_x3))+ self.y2_to_v3*self.v3_to_u3*self.u3_to_z3*self.z3_to_x3


In [82]:
res = Computational_Graph()
res.forward(1,1,1)
res.backward()

print(f"1,1,1 输入的雅可比行列式为 \n {res.y1_to_x1} {res.y1_to_x2} {res.y1_to_x3} \n {res.y2_to_x1} {res.y2_to_x2} {res.y2_to_x3}")

y1 = 24.490479942112778, y2 = 0.6766170068463221
1,1,1 输入的雅可比行列式为 
 55.76452114990751 29.056029435566057 -13.630322852587943 
 -9.55244091025101 -4.475992380884129 -1.1360836488405153


In [83]:
res = Computational_Graph()
res.forward(2,1,3)
res.backward()

print(f"2,1,3 输入的雅可比行列式为 \n {res.y1_to_x1} {res.y1_to_x2} {res.y1_to_x3} \n {res.y2_to_x1} {res.y2_to_x2} {res.y2_to_x3}")

y1 = 64.08711522201764, y2 = -6.078667517564845
2,1,3 输入的雅可比行列式为 
 45.248661012182595 27.320405391278015 -24.266426122991554 
 25.74837188319024 0.061386213049383465 23.646691702463592


In [84]:
res = Computational_Graph()
res.forward(-1,-1,-3)
res.backward()

print(f"-1,-1,-3 输入的雅可比行列式为 \n {res.y1_to_x1} {res.y1_to_x2} {res.y1_to_x3} \n {res.y2_to_x1} {res.y2_to_x2} {res.y2_to_x3}")

y1 = 8.170384423581151, y2 = -0.05974457002445096
-1,-1,-3 输入的雅可比行列式为 
 -34.72443898265999 -17.096059449164276 5.658613307843439 
 -4.530696293583008 -0.37929353394875487 -0.43903810397320575


## 1.2 pytorch实现

In [85]:
import torch

class Net(torch.nn.Module):
    def forward(self, x):
            x1 = x[0]
            x2 = x[1]
            x3 = x[2]

            z1 = 2*x1 + x2
            z2= x1 * 3 * x3   
            z3 = -x3

            u1 =  torch.sin(z1)
            u2 = (2 * x3)+z2
            u3 =(2 * z1) + z3

            v1 = u1 - u3
            v2 = torch.sin(-1*u2)      
            v3 = u1 * u3

            y1 =  v1**2 + v2**3
            y2 =  v2*v3

            return y1,y2


In [86]:
x = torch.tensor([1,1,1], dtype=float, requires_grad=True)
model = Net()
out_1, out_2 = model(x)

out_1.backward()

print(x.grad)

x = torch.tensor([1,1,1], dtype=float, requires_grad=True)
model = Net()
out_1, out_2 = model(x)

out_2.backward()

print(x.grad)

tensor([ 55.7645,  29.0560, -13.6303], dtype=torch.float64)
tensor([-9.5524, -4.4760, -1.1361], dtype=torch.float64)


In [87]:
x = torch.tensor([2,1,3], dtype=float, requires_grad=True)
model = Net()
out_1, out_2 = model(x)

out_1.backward()

print(x.grad)

x = torch.tensor([2,1,3], dtype=float, requires_grad=True)
model = Net()
out_1, out_2 = model(x)

out_2.backward()

print(x.grad)

tensor([ 45.2487,  27.3204, -24.2664], dtype=torch.float64)
tensor([25.7484,  0.0614, 23.6467], dtype=torch.float64)


In [88]:
x = torch.tensor([-1,-1,-3], dtype=float, requires_grad=True)
model = Net()
out_1, out_2 = model(x)

out_1.backward()

print(x.grad)

x = torch.tensor([-1,-1,-3], dtype=float, requires_grad=True)
model = Net()
out_1, out_2 = model(x)

out_2.backward()

print(x.grad)

tensor([-34.7244, -17.0961,   5.6586], dtype=torch.float64)
tensor([-4.5307, -0.3793, -0.4390], dtype=torch.float64)


# 任务二 搭建前向神经网络进行分类

In [90]:
# 网络基本结构

# nn_architecture = [
#     {"input_dim": 128, "output_dim":256, "activation": "sigmoid"},
#     {"input_dim": 256, "output_dim": 64, "activation": "sigmoid"},
#     {"input_dim": 64, "output_dim": 9, "activation": "softmax"},
# ]

nn_architecture = [
    {"input_dim": 2, "output_dim":4, "activation": "sigmoid"},
    {"input_dim": 4, "output_dim": 3, "activation": "sigmoid"},
    {"input_dim": 3, "output_dim": 3, "activation": "softmax"},
]

def init_layers(nn_architecture, seed = 99):
    np.random.seed(seed)
    number_of_layers = len(nn_architecture)
    params_values = {}

    for idx, layer in enumerate(nn_architecture):
        layer_idx = idx + 1
        layer_input_size = layer["input_dim"]
        layer_output_size = layer["output_dim"]

        params_values['W' + str(layer_idx)] = np.random.randn(
            layer_output_size, layer_input_size) * 0.1
        params_values['b' + str(layer_idx)] = np.random.randn(
            layer_output_size, 1) * 0.1

    return params_values

print(init_layers(nn_architecture))

{'W1': array([[-0.01423588,  0.20572217],
       [ 0.02832619,  0.1329812 ],
       [-0.01546219, -0.00690309],
       [ 0.07551805,  0.08256466]]), 'b1': array([[-0.01130692],
       [-0.23678376],
       [-0.01670494],
       [ 0.0685398 ]]), 'W2': array([[ 0.00235001,  0.04562013,  0.02704928, -0.14350081],
       [ 0.08828171, -0.05800817, -0.05015653,  0.05909533],
       [-0.07316163,  0.02617555, -0.08557956, -0.01875259]]), 'b2': array([[-0.03734863],
       [-0.0461971 ],
       [-0.08164661]]), 'W3': array([[-0.00451233,  0.01213278,  0.09259528],
       [-0.05738197,  0.00527031,  0.22073106],
       [ 0.03918219,  0.04827134,  0.0433334 ]]), 'b3': array([[-0.17042917],
       [-0.02439081],
       [-0.21397038]])}


In [ ]:
def sigmoid(Z):
    return 1/(1+np.exp(-Z))

def softmax(Z):
    